//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEKODORO.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEKODORO.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Break Time! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BreakTimeStatus {
            get {
                return ResourceManager.GetString("BreakTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is now yours! You can place it from the Decorate menu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BuySuccessMsg {
            get {
                return ResourceManager.GetString("BuySuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BuySuccessTitle {
            get {
                return ResourceManager.GetString("BuySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calendar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CalendarBtn {
            get {
                return ResourceManager.GetString("CalendarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rabbit friend, please choose a name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChooseNameMsg {
            get {
                return ResourceManager.GetString("ChooseNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Congratulations! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CongratsTitle {
            get {
                return ResourceManager.GetString("CongratsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag items to move them. The app will remember their positions! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DecorateMsg {
            get {
                return ResourceManager.GetString("DecorateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decoration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DecorateTitle {
            get {
                return ResourceManager.GetString("DecorateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You earned {0} coins! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EarnedCoinMsg {
            get {
                return ResourceManager.GetString("EarnedCoinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EnterNameMsg {
            get {
                return ResourceManager.GetString("EnterNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rabbit Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus Time!  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FocusTimeStatus {
            get {
                return ResourceManager.GetString("FocusTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Great! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GreatBtn {
            get {
                return ResourceManager.GetString("GreatBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horrayy! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HoorayBtn {
            get {
                return ResourceManager.GetString("HoorayBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The rabbit disappeared while choosing a picture: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ImageErrorMsg {
            get {
                return ResourceManager.GetString("ImageErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language updated successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LangChangedMsg {
            get {
                return ResourceManager.GetString("LangChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GO IN ♡ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainGoInBtn {
            get {
                return ResourceManager.GetString("MainGoInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MY PROFILE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainProfileBtn {
            get {
                return ResourceManager.GetString("MainProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoBtn {
            get {
                return ResourceManager.GetString("NoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You need more pomodoros! 🥕 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotEnoughCoinsMsg {
            get {
                return ResourceManager.GetString("NotEnoughCoinsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not enough coin.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotEnoughCoinsTitle {
            get {
                return ResourceManager.GetString("NotEnoughCoinsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ra-Rabbit Error.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PawsErrorTitle {
            get {
                return ResourceManager.GetString("PawsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Hour (10 Coins) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pomo1Hour {
            get {
                return ResourceManager.GetString("Pomo1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Hours (25 Coins) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pomo2Hours {
            get {
                return ResourceManager.GetString("Pomo2Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30 Minutes (5 Coins) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pomo30Min {
            get {
                return ResourceManager.GetString("Pomo30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PomoBtn {
            get {
                return ResourceManager.GetString("PomoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROFILE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PopupTitle {
            get {
                return ResourceManager.GetString("PopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile updated benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProfileUpdatedMsg {
            get {
                return ResourceManager.GetString("ProfileUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give Up.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string QuitBtn {
            get {
                return ResourceManager.GetString("QuitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your progress will be lost. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string QuitConfirmMsg {
            get {
                return ResourceManager.GetString("QuitConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are You Sure? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string QuitConfirmTitle {
            get {
                return ResourceManager.GetString("QuitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All coins and items will be deleted. Are you sure? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetConfirmMsg {
            get {
                return ResourceManager.GetString("ResetConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetConfirmTitle {
            get {
                return ResourceManager.GetString("ResetConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All Data benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetData {
            get {
                return ResourceManager.GetString("ResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data cleared. Returning to main page. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetSuccessMsg {
            get {
                return ResourceManager.GetString("ResetSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Successful benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetSuccessTitle {
            get {
                return ResourceManager.GetString("ResetSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectLangTitle {
            get {
                return ResourceManager.GetString("SelectLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Duration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectTimeTitle {
            get {
                return ResourceManager.GetString("SelectTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsBtn {
            get {
                return ResourceManager.GetString("SettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shop benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShopTitle {
            get {
                return ResourceManager.GetString("ShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
